[package]
name = "alif-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bufstream = "0.1"
#futures = "1"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]
